<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita4ea07eccd148d47bab882c44deda28e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'N' => 
        array (
            'Notification\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Notification\\' => 
        array (
            0 => __DIR__ . '/../..' . '/_app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita4ea07eccd148d47bab882c44deda28e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita4ea07eccd148d47bab882c44deda28e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
